# This is a basic workflow to help you get started with Actions

name: SAP CI

# Controls when the workflow will run
on:
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |          
          curl -X POST "https://6f26792atrial.authentication.us10.hana.ondemand.com/oauth/token" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "grant_type=client_credentials" \
            -d 'client_id=sb-da4238df-5d84-4344-9610-6acf626ae0ac!b422594|it-rt-6f26792atrial!b26655' \
            -d 'client_secret=c25209a2-b9a6-4df7-9c49-e7b997e92bac$qrVgQQrhyeXhDWNOmA_gkMRMx9mbX1TwA58yCzK-0kI=' |jq -r '.access_token'
