name: Integration build
'on':
  workflow_call:
    secrets:
      ACTION_GITHUB_ACCESS_TOKEN:
        required: true
      AZURE_TEAMS_NOTIFIER_URL:
        required: true
      CICD_SONAR_LOGIN:
        required: true
      CICD_BLACKDUCK_API_TOKEN:
        required: true
      HPFORTIFY_CTRL_TOKEN:
        required: true
      HPFORTIFY_CI_TOKEN:
        required: true
      HPFORTIFY_DOWNLOAD_TOKEN:
        required: true
      HPFORTIFY_UPLOAD_TOKEN:
        required: true
env:
  PR_NUMBER: '${{ github.event.pull_request.number }}'
  RUN_ID: '${{ github.run_id }}'
  GITHUB_ACCESS_TOKEN: '${{ secrets.ACTION_GITHUB_ACCESS_TOKEN }}'
  GITHUB_API_URL_REST: 'https://github.deutsche-boerse.de/api/v3'
  GITHUB_API_URL_GRAPHQL: 'https://github.deutsche-boerse.de/api/graphql'
  AZURE_API_URL: '${{ secrets.AZURE_TEAMS_NOTIFIER_URL }}'
jobs:
  checkChangedFiles:
    runs-on: ubuntu-latest
    steps:
      - name: Get changed files
        id: getChangedFiles
        run: |
          sleep 120
          echo "workflow executed"
