name: test npm
on:
  workflow_dispatch:
jobs:
  npm-test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          
      - name: Install iflow-plotter
        run: |
          npm install -g iflow-plotter
